- source/common/searchpaths.cpp
I know 32-bit is not officially supported, but it compiled successfully with this little fix. I don't foresee filename sizes exceeding 4 billion characters anyhow.
> - fix compile on 32-bit

- source/common/menu/savegamemanager.cpp
Virtual <New save game> item wasn't taken into account
GZDoom has a different order of calls to `FSavegameManager::RemoveNewSaveNode()` and `FSavegameManager::NotifyNewSave()`. I would like to be sure that it wasn't an occasional change.
> Fix for shifting of the current item in save/load menus

- source/rr/src/player.cpp
Minor tweaks to the last commit. Vehicle was accelerating too quickly and also removed some of the hard-coded values. Left a gap between the new defines and the existing ones to ease future cherry-picking.
- Make localInput.fvel only equal to input.fvel + pPlayer->moto_speed.
- Define MOTOTURN and MAXVELMOTO in line with other defines used throughout P_GetInput*() functions.
- Clamped minimum fvel value is also now correct.
> Repair vehicle acceleration following changes to input handling.

- source/common/gamecvars.cpp
- source/duke3d/src/config.cpp
- source/duke3d/src/game.cpp
- source/rr/src/config.cpp
- source/rr/src/game.cpp
- Resolves https://forum.zdoom.org/viewtopic.php?f=340&t=67811
I tried fixing this by shit-canning the entire config.cpp file and call to CONFIG_ReadSetup() but the intro video for Duke 3D played at full framerate rather than 13fps and it's not obvious why.
EDIT: Alternatively, can the cvar have 'CVAR_NOINITCALL' removed to avoid using Callback()? I chose this route as I assumed the cvar is meant to be like this and I didn't know the overall impact for other games, etc.
> Repair HUD scaling returning to 100% when relaunching Duke or RR games.

- source/common/searchpaths.cpp
- Redneck Deer Huntin' also comes with Redneck Rampage Rides Again.
- Changes permit all games to be detected, including RRRA if you own Deer Huntin'.
> Change detection arrays for Redneck games.

- source/duke3d/src/game.cpp
- source/rr/src/game.cpp
The improvement is very subtle but I can definitely tell the difference. Might be less noticable at refresh rates higher than 60Hz (it's all I have until the AUD gets better).
- Hack code from 9 years ago to break loop early removed. If game code is running slow, that's not the fix.
- Get input and fill the input_t struct in same loop as G_DoMoveThings().
- Remove unnecessary do/while (0) loop.
Some notes on the 'hack code', it might have made sense when it was committed, but when I altered to loop to run as fast as it could on my Core i7 4770k, the game easily ran 5-6 times faster than it should have with vsync on, and many magnitudes faster with vsync off. The shotgun unloaded 50 shells in about 2.5 seconds. It's just not needed.
> Remove last vestiges of input latency from Duke3D and RR main game loops.

- source/sw/src/game.cpp
- source/sw/src/player.cpp
I never play using just the keyboard so I didn't immediately realise at midnight these keys were a bit too sharp in their actions.
This change makes these keys behave as per vanilla, but with all the Q16.16 goodness.
- Input was too aggressive and unlike vanilla.
- Use more scaleAdjustmentToInterval() to rectify.
> SW: Adjust look and snap up/down keys.

- source/sw/src/player.cpp
- Original value was 12 and was far, far too high following the Q16.16 implementation.
- Value of 3 is too fast.
- Value of 2 is too slow.
- Value of 2.4 (12 / 5) feels just right.
If it's too late for the release, it's too late. Apologies but I was just a but unsettled on this. So hard to get all this hard-coded shit just right.
Axis scaling is such a personal thing but I want the game to feel 1:1 with Duke 3D with:
- Mouse sensitivity at '1'.
- in_mousescalex at '1'.
- in_mousescaley at '1'.
I think it does now.
> SW: Get PLAYER_TURN_SCALE to be just right.

- source/blood/src/controls.cpp
- source/blood/src/nnexts.cpp
- source/blood/src/player.cpp
- source/blood/src/view.cpp
This one is more subjective, I guess. I think the horizonal scaling is too fast and others on the forums have agreed with me, but I don't know if it's like that to be accurate to the DOS version. Being a Nuke.YKT project, I'd assume so.
I will leave this one in your good hands for consideration.
- Make scaling more consistent with other games.
- Fix CONSTEXPR to constexpr.
- Remove usage of macro 'F16()' by using explicit fix16_from_*() type.
> Blood: Rebalance q16mlook.

- source/sw/src/draw.cpp
- source/sw/src/game.cpp
- source/sw/src/game.h
- source/sw/src/jweapon.cpp
- source/sw/src/network.cpp
- source/sw/src/player.cpp
- source/sw/src/weapon.cpp
I backported my changes to VoidSW and there's been a few things that NY00123 has changed here and there that make sense so I'm pulling them in just to keep the code base consistent.
I also actually _properly_ fixed the `PLAYER_TURN_SCALE` option by just not using it in DoPlayerTurn(). There's no point multiplying q16avel only to divide it again. Feels proper perfect without the voodoo 'let's change the already processed angle velocity just because' code.
> SW minor tweaks.

- source/sw/src/game.cpp
- ScrollMode2D was running at the frame rate, turning off vsync made it unacceptable.
> SW: Don't process input at frame rate if ScrollMode2D is true.

- source/blood/src/map2d.cpp
- source/sw/src/draw.cpp
This is to work around [this reported issue](https://forum.zdoom.org/viewtopic.php?f=356&t=67744).
For SW, there's so many janky examples of this throughout the game's code. I thought best to remove the subtractions done in [BorderSetView()](https://github.com/coelckers/Raze/blob/6589d316785c20c940d8d11f2be2608cdf92fc8e/source/sw/src/border.cpp#L401) but I've decided to go the safe route due to comments [like this](https://github.com/coelckers/Raze/blob/6589d316785c20c940d8d11f2be2608cdf92fc8e/source/sw/src/border.cpp#L281).
EDIT: Pushed same fix for Blood.
> SW/Blood: Workaround for map view showing 1px of non-border at the bottom.

- source/sw/src/draw.cpp
- source/sw/src/game.cpp
- source/sw/src/game.h
- source/sw/src/player.cpp
- source/sw/src/predict.cpp
Just some minor changes and restoration of some old behaviour.
- Define new function GetDeltaAngleQ16() and use it appropriately.
- Smooth out 180 degree turning.
- Ensure 180 degree turning is always clockwise (thanks NY00123).
- Lock player turning and horizon when dead (thanks NY00123).
- Restore old interpolation when the camera pans while dead (this function runs at the game's ticrate and not frame rate) (thanks NY00123).
> SW minor input refinements

- source/blood/src/controls.cpp
- source/duke3d/src/player.cpp
- source/rr/src/player.cpp
- source/sw/src/game.cpp
It was reported [here](https://forum.zdoom.org/viewtopic.php?f=340&t=67232#p1142970) that after changing the input for Duke 3D and RR that it was still not working on Linux.
Did some testing and changing the button event to ButtonPressed, then ClearButton made this work on Linux, while still working on Windows.
Blood and SW had a similar ClearButton remark which Duke 3D and RR never had, but while SW was working in Windows, Blood was not. Changing Blood to ButtonPressed also has the scroll wheel working now.
I don't believe these are true fixes, merely stop-gaps until something better can be done which you've talked about. This also doesn't resolve issues users might face if they elect to use the scroll wheel for anything other than weapon selection.
> All games weapon selection workaround

- source/platform/posix/unix/gtk_dialogs.cpp
'countof()' was not available.
While it compiles, still having issues running after compile. I trigger I_FatalError in FScanner::CheckOpen(). Will try to work out what's going on and either raise a PR for it or put in a ticket on the forums.
> - Repair compiling on Arch Linux with GCC 9.3.0.

- source/duke3d/src/game.cpp
- source/exhumed/src/exhumed.cpp
- source/rr/src/game.cpp
- source/sw/src/game.cpp
This is to work around the issues reported [here](https://forum.zdoom.org/viewtopic.php?f=340&t=68226) and [here](https://forum.zdoom.org/viewtopic.php?f=345&t=67733).
Because the issue keeps getting 'razed' :wink:, I thought perhaps something could be done to address them. These changes are effectively duplicates of what was done while repairing the main game loop for Exhumed. 
I've also added commits to reset the buttonMap after returning from pause. Currently if you're holding down any key, that key remains stuck down until you press it again (walking, strafing, etc). I think it's desirable to reset that state and not be locked in, but have done as separate commits so that they can be excluded if desired.
> Game pause fixes

- source/duke3d/src/player.cpp
- source/duke3d/src/premap.cpp
- source/rr/src/player.cpp
- source/rr/src/premap.cpp
- source/sw/src/game.cpp
A few things going on here.
SW: The bits that set whether the player is aiming up/down, etc was being set after the code to perform the action. Setting prior allows the action to be performed within that iteration of the function and not the next frame.
Duke3D & RR: With both games while cherry-picking the input changes that do mouse input at the frame-rate, a deletion was missed that was causing the player not to return to centre upon a hard landing. This is original behaviour so it should be restored.
Following the repair, I note that when re-centering from a hard landing, the player cannot look up/down until `thisPlayer.horizRecenter` is `false`. Because this was being done within the game's clock in `P_ProcessInput()`, it was slow and gave this jarring effect of not being able to aim …
> Game input tweaks

- source/duke3d/src/game.cpp
- source/exhumed/src/exhumed.cpp
- source/rr/src/game.cpp
- source/sw/src/game.cpp
Apologies, my fix worked a little too well. Noticed this morning that the spinning menu animations for Duke 3D/SW weren't spinning as intended.
This change still pauses the game cleanly when going into a GUI break (console, etc) but keeps the clock running so interpolations still work.
> - allow game's clock to keep running while paused (restores interpolations/animations in menus).

- source/duke3d/src/game.cpp
- source/rr/src/actors.cpp
- source/rr/src/game.cpp
Backport of an EDuke32 fix as well as the new implementations. Makes the camera smooth when chasing the actor who whacked you, which is done at ticrate and not frame rate.
> Death cam fixes

- source/core/version.h
- source/duke3d/src/player.cpp
- source/duke3d/src/player.h
- source/exhumed/src/player.cpp
- source/rr/src/player.cpp
- source/rr/src/player.h
- source/sw/src/game.cpp
Reverted some previous commits regarding better handling of returning to centre for Duke 3D and RR. Previous attempt wasn't the best as return to centre speed fluctuated with frame-rate, etc. What's here feels much more consistent and is very nice from a game-play point of view.
Other fixes are properly scaling the tilt angle for the motorbike and hovercraft in RRRA. Previously the tilt speed increased as the frame-rate did. Also backported some EDuke32 input improvements to the other games.
> More misc input improvements

- source/exhumed/src/player.cpp
Value was accidentally set incorrectly.
> Exhumed: Set scaleAdjustmentToInterval to correct value for game's ticrate.

- source/duke3d/src/player.cpp
- source/duke3d/src/player.h
- source/duke3d/src/premap.cpp
- source/rr/src/player.cpp
- source/rr/src/player.h
- source/rr/src/premap.cpp
Best that this data not be in the DukePlayer_t struct since it's data that never needs to be sent to other clients in a multiplayer situation.
Having this in the playerdata_t struct is also in line with where all the new properties concerning input being tied to frame-rate are kept.
> Duke3D and RR: Move lastInputTicks to a different struct.

- source/core/version.h
Forgot about this in my previous PR. Previous saves are inoperable with the changes that have been made.
I bumped the save game ver for RR in a previous commit for the same reason. Since the changes are all within a release cycle, I won't bump it again.
> Bump save versions for Duke3D following changes to DukePlayer_t struct.

- source/sw/src/draw.cpp
What 43ec16eb5576124bed3699943bb70b9ea943bd93 intends to do was already done via 2d734664259e47b999fe989b924ecaa0a97bb109, however I applied the if statement in the opposite order so when it was cherry-picked again, the pathway was actually reversed - interpolating when alive and not when dead.
Rather than re-apply the opposite order, I've made the if statement match upstream for more consistency and to avoid further conflicts.
> SW: Fix broken interpolation pathway

- source/sw/src/draw.cpp
- source/sw/src/game.cpp
- source/sw/src/game.h
- source/sw/src/player.cpp
- source/sw/src/player.h
When making the player's input change at frame-rate, the code for `DoPlayerTurn()` and `DoPlayerHorizon()` were moved into `getinput()` as required. However, this caused some issues when operating vehicles as you'd have the vehicle code updating angle as well as `getinput()`.
These changes make the vehicles operate nicely, nicer than they do before this PR and nicer than they did in 0.5.1. In saying that, input for these is processed with the game's tic-rate. They're too complicated to move, it's more accurate to just do those corner cases at tic-rate.
> SW input improvements

- source/core/gamecvars.cpp
- source/core/gamecvars.h
- source/sw/src/draw.cpp
- source/sw/src/game.cpp
- source/sw/src/interpso.cpp
- source/sw/src/settings.h
- source/sw/src/track.cpp
New code is causing some issues that are being worked on, particularly a secret in $bullet/Level 1: Seppuku Station and the drill in $dozer/Level 2: Zilla Construction.
Upstream do expose this as a menu toggle, but I feel it's more for debugging than anything else. Can expose through the menu similar to `cl_slopetilting` if desired.
> SW: Allow sector object interpolations to be disabled for debugging.

- source/core/inputstate.cpp
- source/core/inputstate.h
- source/duke3d/src/player.cpp
- source/exhumed/src/player.cpp
- source/rr/src/player.cpp
- source/sw/src/game.cpp
* Repairs https://forum.zdoom.org/viewtopic.php?f=340&t=67239 and https://forum.zdoom.org/viewtopic.php?f=340&t=67933
* Values that come from GZDoom backend are too low to be suitable for the Build games which were dividing by 'analogExtent'.
* Remove definition of analogExtent from all games and define in inputstate.h, then define joyaxesScale as 75% of analogExtent to provide a bit of headroom and not have a scale of 1.0 be full speed.
* Invert the returned results of GetAxes() as the returned floats are reversed for build games.
* Leverage scaleAdjustmentToInverval() on game-side code to consistently scale the input irrespective of frame rate, vsync etc.
> - fix joystick scaling for all games.

- source/blood/src/blood.cpp
- source/blood/src/controls.cpp
- source/blood/src/controls.h
- source/blood/src/network.cpp
Repairs interpolation issues introduced in 96c9ca657ea349e01edef46fe4fda8fd75d90906 as reported in https://forum.zdoom.org/viewtopic.php?f=340&t=69009.
It seems this [missed commit](https://github.com/nukeykt/NBlood/commit/a189828bfc8ab976a9ce955363cccdb5e63de511) was the cuprit. I edited the commit heavily during the cherry pick process to move all the 'frameJustDrawn' crap.
> Blood: input code improvements

- source/blood/src/view.cpp
- source/build/src/polymost.cpp
- source/core/gamecvars.cpp
- source/core/gamecvars.h
- source/duke3d/src/game.cpp
- source/exhumed/src/osdcmds.h
- source/rr/src/game.cpp
This is to address the issues raised [here](https://forum.zdoom.org/viewtopic.php?f=340&t=68838).
The lighting level was only controllable for Duke3D and RR. The first commit makes r_ambientlight effective for all games and not just the aforementioned.
The second commit fixes the default lighting value back to what it was prior to 0bd460d9e3bbaf239f4a33f9ce589dff58660bea.
* Output from PrintVis() in 9dfd3ddd02631f9362e2d61211d92ef5b26c3a69 showed resulting global visibility as 0.078125.
* Following 0bd460d9e3bbaf239f4a33f9ce589dff58660bea, resulting global visibility shown as 0.041667.
* Scaling g_visibility by (8.f / 15.f) (0.533333) restores resulting global visibility to 0.078125.
Please test and let me know how things look on your end.
> Fix default global visibility value and make r_ambientlight work for all games.

- source/sw/src/game.cpp
This was pushed in https://github.com/coelckers/Raze/pull/20, but ended up being reverted when rebasing framerate-based input on upstream's implementation.
This was reported by Kinsie, who tested a build with this commit re-applied and confirmed it resolved the issues he was experiencing.
> Change Next/Previous Weapon button handling for Shadow Warrior.

- source/common/console/c_bind.cpp
Probably more of a subjective change, but the preset named default should be the out-of-box default in my mind. It's also one of the first things I change on a fresh configuration.
> - change cl_defaultconfiguration default from '2' (leftbinds) to '0' (defbinds).

- source/blood/src/controls.cpp
- This means that while weapons can't be changed mid-animation, they switch consistently. I feel they animate quick enough, anyway.
> Blood: Fix issues with weapon not switching properly if cycling the weapons too quickly.

- source/build/src/polymost.cpp
More stylistic than anything else. Achives an identical result from the test spot I've been using with a simpler algorithm that's easier to read.
> - simplify visibility calculation from changes performed in d80a32d37905e12e57d2c2e86097290dbf236114.

- source/blood/src/controls.cpp
- source/core/inputstate.cpp
- source/core/inputstate.h
- source/duke3d/src/player.cpp
- source/exhumed/src/player.cpp
- source/rr/src/player.cpp
- source/sw/src/game.cpp
- source/sw/src/player.cpp
* Convert axes in ControlInfo struct from int32_t to float as what's received from the backend.
* Remove all the scale up/down math since we don't need that with floats and replace with float constants that match old behaviour.
* Store q16mlook scaling as a constant for use with mouse and upcoming controller code.
* Add required controller code to Blood as the only game not to have working controllers.
* Fix typos in (gInput.forward > input.forward) for `ctrlGetInput()` in Blood.
* Remove use of `scaleAdjustmentToInterval()` on Exhumed and Shadow Warrior as they only process forward/side velocities within the game's ticrate.
* Repair angvel/aimvel scaling mistakes from d79a5d256d7593a3633759f302ebc33cc7710ecb.
* Scale dyaw and dpitch by 25% for Shadow Warrior as the game runs 25% faster …
> - make controller input identical across all games.

- source/build/include/polymost.h
- source/build/src/engine.cpp
- source/build/src/polymost.cpp
* Changes performed in 0bd460d9e3bbaf239f4a33f9ce589dff58660bea didn't take into account xdimenscale and viewingrangerecip like the days of old and this wasn't picked up in d80a32d37905e12e57d2c2e86097290dbf236114 or d80a32d37905e12e57d2c2e86097290dbf236114, where the applied fixes only appeared to work because they worked for me at 2560x1440p.
* Remove calculation of (7.5f / (65536.f * 65536.f)) which needed to become (1.f / (65536.f * 65536.f)) and just the actual value.
See https://forum.zdoom.org/viewtopic.php?f=341&t=68838 for discussion.
> Visibility Fix, Option #1

- source/common/platform/posix/sdl/i_input.cpp
Under Windows, when `m_noprescale` is false, the x value is bit shifted by 2 (4x original) and the y value is never touched. Under SDL, when `m_noprescale` is false, the x value is 3x original and the y value is 2x original.
This fits in perfectly with how I'd always set in_mousescaley to 0.5 and then set in_mousesensitivity to 1.25 when playing under Linux. With these changes, the mouse feels 1:1.
> - make SDL mouse scaling match that of Windows for consistency.

- source/glbackend/glbackend.cpp
* Will be useful for further debugging of the lighting to determine whether Build actually did/does do different visibility for floor/walls/ceilings, etc.
* Idea inspired by Gez: https://forum.zdoom.org/viewtopic.php?f=341&t=68838&start=75#p1158294
> - add `gl_texture` CVAR to glbackend à la GZDoom.

- source/blood/src/controls.cpp
- source/core/inputstate.cpp
- source/core/inputstate.h
- source/duke3d/src/player.cpp
- source/exhumed/src/player.cpp
- source/rr/src/player.cpp
- source/sw/src/game.cpp
When I was looking at all the controller code, I thought the mouse movement code would be better off being a float for more precision. If we're going to implicitely convert it to float by dividing it by float-type CVARSs, might as well maintain it.
Overall the game code has been simplified in the process as rather than dividing mousex/y by 32/64 respectively, the appropriate scaling is done in `GetMouseDelta()`.
* Calculate game-side mousex/mousey divisions into the calculations performed in `InputState::GetMouseDelta()`.
* Standard mouse forward/side movement speeds in Exhumed & SW with that of other games.
* Remove `strafeyaw` code from Duke/Exhumed/RR as it's not necessary and was leading to situations where the player would continually keep moving sideways even without input.
* Change …
> - change mouse input from int to float and adjust games accordingly.

- source/glbackend/glbackend.h
* This fixes some issues with distance lighting issues in Duke3D as reported at https://forum.zdoom.org/viewtopic.php?f=341&t=68838&start=75#p1158417.
* Implemented as inline if as max() was not available and didn't want to drag a header in for one thing.
> - allow shade in glbackend.h to accept negative values, but still at a max of numshades-1

- wadsrc/static/engine/menudef.txt
This just adds a menu entry for the existing toggle to improve its visibility to the user.
Took me a few centuries to realize how to add a simple string to it...
> - menu entry for the alternative nuke initialization toggle in SW

- source/blood/src/eventq.cpp
- source/blood/src/triggers.cpp
This PR fixes two following bugs:
1. Sectors that move through a path (sector type 612) do not work, due to path markers (sprite type 15) being looked for in the wrong statlist.
2. Events with negative priority break map event queue processing, completely preventing any map events from being handled.
During map initialization, some sprites can add an event with negative priority, for example, [general trigger (sprite type 700)](https://github.com/coelckers/Raze/blob/master/source/blood/src/triggers.cpp#L2216), or water/blood drip (sprite type 701/702). Despite being highest priority events, [comparison with with the game timer](https://github.com/coelckers/Raze/blob/master/source/blood/src/eventq.cpp#L560) returns false even at tick 0 due to an implicit unsigned cast, which stops event …
> [Blood] Fix negative priority event processing, fix sector path markers not working

- source/core/gamecontrol.cpp
Fixes terminal output cutoff on console tab completion on Unix systems.
> Destroy FStartupScreen before initializing video

- source/build/include/build.h
- source/build/src/engine.cpp
A memset exceeded the array bounds.  I assumed the memset was correct and expanded the array.
> Fix buffer overflow at maploader.cpp:392

- source/core/razefont.cpp
Bug fix for small fonts on ARM when using Clang. Not sure why it seems to work on Windows builds without this fix.
> Fix so small font is displayed correctly

- wadsrc/static/menudef.txt
`r_ambientlight` works in a way similar to EDuke32's Visibility slider. Higher values decrease the amount of visible "fog" in the distance, especially in darker areas.
See https://github.com/coelckers/Raze/issues/432.
> Add an Ambient Light slider to the Display Options setting GUI

- source/build/src/polymost.cpp
This never actually did what it was supposed to. The function `sepdist()` has also been removed since.
> Remove useless code introduced in bad17f29

- source/common/platform/posix/sdl/sdlglvideo.cpp
This is necessary so the in-use resolution is used as the window size for Vulkan windows when they are fullscreen.
This is already done in GL windows, it's just that this flag was missing from Vulkan windows.
It's specially important because Vulkan on KMSDRM (=no X11) only supports windows with a matching physical resolution available.
> Pass the missing fullscreen flag when creating a Vukan window.

- source/games/blood/src/weapon.cpp
This fixes the bug when switching from spray can to TNT and back before the animation has completed.
The bug in question:
https://user-images.githubusercontent.com/38839485/129200775-d83b78f3-b95c-4a81-a925-007d0e916975.mp4
> Fix spray can animation bug

- source/games/blood/src/weapon.cpp
This will fix the issues of using next/prev weapon inputs underwater. For both NBlood/Dos this issue remains intact while BloodGDX has fixed it.
When underwater it would always skip the telsa cannon and select the proxy remote when using next weapon, and when trying to pick previous weapon it'll be stuck on the telsa cannon. With this fix it'll skip over the banned weapons and keep the weapon scroll behavior the same as when on land.
https://user-images.githubusercontent.com/38839485/129360258-0c1d14c5-6752-482f-ad8c-b92d042baff0.mp4
https://user-images.githubusercontent.com/38839485/129360348-0b1bc267-08a0-4df3-8836-8fc92a9baf76.mp4
> [Blood] Tweaked next/prev weapon behavior underwater

- source/games/blood/src/actor.cpp
- source/games/blood/src/ai.cpp
This PR fixes the following issues
* All cultists randomly switching between shotgun/tommy gun types when extinguished in water
* Tiny Caleb enemy using incorrectly scaled innocent burning sprite type when ignited
* Rare chance of enemies outlasting burn timer damage and locking them in a state of burning
Cultists will now restore back to their original type when extinguished in water (only if inittype is valid). This will work for all cultists types, including telsa if you manage to ignite them and let them fall in water.
Tiny Caleb will now use the unused sprite type `kDudeBurningTinyCaleb` as well as AI functions for burning tiny Caleb.
All burning enemies will have damage applied to their state every tick, even if burn time has reached zero.
All of these changes check with …
> [Blood] Fix various issues with burning enemies

- source/games/blood/src/actor.cpp
This PR will prevent the fall scream triggering if the player has died.
https://user-images.githubusercontent.com/38839485/129496887-0340c971-d9c9-47a8-a7e6-389d7f645890.mp4
https://user-images.githubusercontent.com/38839485/129496893-348c13b1-c95c-4d42-afe2-396358cceb5c.mp4
> [Blood] Don't trigger fall scream if player is dead

- source/games/blood/src/actor.cpp
This PR fixes a bug introduced with the new accurate clipmove() feature.
For the bloated butchers, their kMissileButcherKnife missile attack will instantly collide with itself after spawning. This is fixed by setting the missile's collision off before calling clipmove(), and restoring cstat (like how Blood does with projectile's owner).
https://user-images.githubusercontent.com/38839485/130475800-f0479dcb-f968-4c53-8d83-46fd4cfbb754.mp4
https://user-images.githubusercontent.com/38839485/130475949-3fef2800-352a-45c5-adac-aa7ce7d484de.mp4
> [Blood] Prevent missiles from self colliding on MoveMissile()

- source/games/blood/src/misc.h
- source/games/blood/src/player.cpp
- source/games/blood/src/triggers.cpp
- source/games/blood/src/weapon.cpp
This PR fixes a weapon state glitch when collecting a dropped life leech with an ignited TNT/spray can. Instead now it'll first check if TNT/spray can is active, and if true will not forcefully switch weapon to life leech.
https://user-images.githubusercontent.com/38839485/131180401-18ca35e0-278c-4360-a586-341fd55a3065.mp4
https://user-images.githubusercontent.com/38839485/131182619-426e0421-6516-468a-a746-b9a6a9ef95ba.mp4
> [Blood] Fix weapon state glitch when collecting dropped life leech

- source/common/rendering/gles/gles_renderstate.cpp
It seems mBias.mChanged can become out of sync, so ignore for now for gles.
> GLES: Fix bias state

- source/games/blood/src/sectorfx.cpp
This PR fixes the incorrect direction used for non-relative ceiling panning sectors as described in issue https://github.com/coelckers/Raze/issues/649.
I've attached a before/after along with the modified test level used for the video examples.
https://user-images.githubusercontent.com/38839485/153956033-44a907a4-50f5-4bf7-be23-3bc06e7a6c91.mp4
https://user-images.githubusercontent.com/38839485/153956195-66011299-6361-44b9-bff6-66c4d4d72a6d.mp4
[test.zip](https://github.com/coelckers/Raze/files/8064344/test.zip)
> [Blood] Fix ceiling panning angle

- source/games/blood/src/aicult.cpp
This PR fixes the state bug for tesla cultists. By default when a tesla cultist goes into prone state they'll fire indefinitely and not break out of it. By setting the think function reference this will force the cultist to stand back up and continue functioning.
https://user-images.githubusercontent.com/38839485/157251340-ce0ed6a2-45ab-41ac-9a5d-af9cce1531f8.mp4
https://user-images.githubusercontent.com/38839485/157251444-72bfe78a-ab18-47b9-be12-71f5077cc716.mp4
> [Blood] Fix tesla cultist prone state

- source/common/engine/m_joy.cpp
When shutting down with no game data, GameConfig is saved and the
pointer is nulled. If a joystick was present, a null dereference occurs
when the engine tries to save the joystick config later in the shutdown
sequence.
Add a check to avoid a crash in this scenario.
> Fix crash when exiting with no game data

- source/common/platform/posix/sdl/i_system.cpp
If KDE is running but kdialog is not present on the system (e.g. as is
the case on SteamOS), allow falling back on the GTK dialogs instead.
> Improve KDE/kdialog detection

- source/core/gameconfigfile.cpp
The default paths for **FileSearch.Directories** and **SoundfontSearch.Directories** are somewhat broken.
`SHARE_DIR` is defined as just `/usr/local/share/`.
The paths `…/games/raze` are not added to **FileSearch.Directories**.
`GAME_DIR` is defined as `.config/raze` on Unix. Combining it with the prefix `…/share/` is wrong.
Excerpt from the default configuration:
```ini
[FileSearch.Directories]
…
Path=/usr/local/share/
…
[SoundfontSearch.Directories]
…
Path=/usr/local/share/.config/raze/soundfonts
Path=/usr/local/share/games/.config/raze/soundfonts
Path=/usr/share/.config/raze/soundfonts
Path=/usr/share/games/.config/raze/soundfonts
```
> Fix broken paths in default configuraiton on Unix

- source/games/exhumed/src/player.cpp
I'm guessing the `nWalls < -1` is a typo, and it should have been `nWalls <= -1` all along. I decided to write `nWalls < 0` instead.
I don't know if I broke anything with this commit, but hopefully everything else still works as intended.
> Attempt to fix #647

- source/core/defparser.cpp
- source/core/textures/tilesetbuilder.cpp
Default-initialize TilesetBuildInfo `info` in tilesetbuilder.cpp
Also, make every function in defparser.cpp static except for loaddefinitionsfile, since that's the only function which is called from other source files
> Attempt to fix #806

- .github/ISSUE_TEMPLATE/bug_report.yml
Since saved games are the preferred way for Raze developers to reproduce bugs.
> Impel people to include saved games in bug reports

- wadsrc/static/filter/dukelike/rmapinfo.spawnclasses
Otherwise, maps like E2L2 will have missing keycards
> Keycards need the noskill flag

- source/core/searchpaths.cpp
Adds the following GOG registry paths to locate games from GOG:
- Duke Nukem 3D Atomic Edition (no longer sold on GOG)
- Blood: One Unit Whole Blood (no longer sold on GOG)
- Shadow Warrior Classic Complete (Free! on GOG)
There are also three I scraped from their store pages, but commented out because I don't own them so can't verify if they need any additional search paths or not:
- Redneck Rampage Collection
- NAM
- Shadow Warrior Classic Redux
> Add more GOG registry search paths

- libraries/ZVulkan/include/zvulkan/vk_mem_alloc/vk_mem_alloc.h
- libraries/ZVulkan/src/vulkanbuilders.cpp
- libraries/ZVulkan/src/vulkanswapchain.cpp
These probably used to get included indirectly internally.  Fixes build on Fedora 38.
> Fix build on recent gcc/libstdc++

- source/games/exhumed/src/2d.cpp
`plasma_A[5] = {};` will write the default value for int to the sixth element of plasma_A, causing a `global-buffer-overflow`.
I assume the intention here was to fill these three arrays with zeroes, which is what I did with the memset calls.
> Fix a memory write issue with plasma_{A,B,C}

- .github/workflows/appimage.yml
- .gitignore
- AppImageBuilder.yml
I believe this is good enough to look at for a PR, refer to #678 I imagine there might be some things I'm not quite doing right with Raze itself. I've only tested it against running Duke Nukem 3d 
I tested this locally using [nektos/act](https://github.com/nektos/act) and on github actions directly,
https://github.com/fang64/Raze/actions/runs/3784997258
I've generated a appimage binary that is working under Ubuntu 22.04 LTS and on Arch, it seems to run fine under Wayland and Xorg.
Built AppImage: https://github.com/fang64/Raze/suites/10065608383/artifacts/490030840
> Add Linux Appimage Build Workflow

- .gitignore
- Raze counterpart of https://github.com/ZDoom/gzdoom/pull/2496.
This prevents accidentally committing this file if you run into a crash while working on something.
> Add crash log file to `.gitignore`

- source/platform/posix/org.zdoom.Raze.desktop
PrefersNonDefaultGPU is currently very broken, see https://github.com/ValveSoftware/steam-for-linux/issues/9940
> Remove PrefersNonDefaultGPU from desktop file
