source/blood/src/demo.cpp
source/common/gamecontrol.cpp
source/common/gamecontrol.h
source/common/savegamehelp.cpp
source/duke3d/src/demo.cpp
source/platform/posix/osx/i_specialpaths.mm
source/platform/win32/i_specialpaths.cpp
source/rr/src/demo.cpp

The current game subdirectory is now created on all platforms
`cl_savedir` CVAR and `-savedir` command line switch are supported on all platforms

Unified saved games and demos paths handing for all platforms

---

source/rr/src/player.cpp

This seemed to be missed on the previous PR, perhaps as it was not in the initial push but in subsequent ones. The vehicles turn way too fast without adjusting the function as per this PR.
- Calculate turnAmount in 1st 'if (turn)' statement to save on a 2nd.
- Divide all subsequent values from turnAmount for cascasing effect.
- Rearrange some code to save on if statements checking the same condition.
- Remove q16horz code since player has no vertical movement on a vehicle.
- Remove horizAngleAdjust code as it's not necessary and has a jarring effect.

Repair vehicle input functions following changes to input handling.

---

source/sw/src/demo.cpp
source/sw/src/draw.cpp
source/sw/src/game.cpp
source/sw/src/game.h
source/sw/src/jplayer.cpp
source/sw/src/jsector.cpp
source/sw/src/jsector.h
source/sw/src/jweapon.cpp
source/sw/src/mclip.cpp
source/sw/src/network.cpp
source/sw/src/ninja.cpp
source/sw/src/player.cpp
source/sw/src/predict.cpp
source/sw/src/rooms.cpp
source/sw/src/sector.cpp
source/sw/src/sounds.cpp
source/sw/src/sync.cpp
source/sw/src/track.cpp
source/sw/src/weapon.cpp
source/sw/src/zombie.cpp

Worked on this all weekend, much to the annoyance of my woman...
Highlights are:
- Increased resolution for mouse using Q16.16.
- Input processed at frame rate.
Input feels as responsive as Duke 3D/RR but the angle/X-axis isn't quite as smooth. Still worthy of submission for review.
I'd also consider doing a new release soon. This, the Duke 3D/RR input stuff that got backported + RRRA not working in the last released version are all significant factors.

SW input improvements

---

source/duke3d/src/game.cpp
source/rr/src/game.cpp

Separated from a previous PR you knocked back for having cross-game changes.
This is really just a refinement on top of PR #21 to make the code easier to and remove some duplication. The if statement guarding the original do/while loop isn't needed when a while loop can contain the same conditions and either run one or many times, or none.
- Replace if statement containing nested do/while loop with a while loop.

Further improve Duke3D and RR main game loop.

---

source/sw/src/draw.cpp
source/sw/src/game.cpp
source/sw/src/game.h
source/sw/src/jplayer.cpp
source/sw/src/jsector.cpp
source/sw/src/player.cpp
source/sw/src/track.cpp

Smooth as butter. Apologies for holding up the release.
- videoNextPage() moved to after restoring interpolations.
- Properly use Q16.16 in as many places as possible. This fixes the angle/X-axis issues.
- Remove unnecessary call to timerUpdate() in main loop, only needs calling once and is called by eventhandlers().

SW: Refinements to new input code.

---

source/blood/src/blood.cpp
source/blood/src/controls.cpp
source/blood/src/controls.h
source/blood/src/demo.cpp
source/blood/src/map2d.cpp
source/blood/src/map2d.h
source/blood/src/network.cpp
source/blood/src/network.h
source/blood/src/player.cpp
source/blood/src/view.cpp

Cherry picked and worked through the merge conflicts to produce a result. Game works well and issues that Nuke.YKT says occur with 180 spin and look up/down aren't apparent in Raze.
Only played through half the first level but feels great.

Blood input improvements

---

source/sw/src/game.cpp
wadsrc/static/engine/menudef.txt

Just some minor cleanups. Most importantly is the mouse sensitivity slider that's currently broken.

Minor fixes

---

source/exhumed/src/exhumed.cpp
source/exhumed/src/player.cpp
source/exhumed/src/player.h
source/exhumed/src/ps_input.h
source/exhumed/src/view.cpp
source/exhumed/src/view.h

I figured if you haven't released yet, might as well do the last game... This one was pretty annoying to do as the input wasn't running right to begin with.
~~This isn't in a merge-ready state and requires a further commit that I'll have to get to once I've had family time this weekend. More sending this through now to say that I have this and am working on it if you want it in prior to a release.~~
Fixes:
- Input velocity now consistent irrespective of frame rate.
- Angle and horizon calculated at frame rate.
- Replace usage of F16() macro with fix16_from_int() in GetInterruptKeys().
~~Issues:~~
~~- Look up/down keys are not yet working.~~

Exhumed input improvements

---

source/common/menu/optionmenuitems.h

- Resolves 'https://forum.zdoom.org/viewtopic.php?f=340&t=67721'.

Menu System: Add confirmation to FOptionMenuItemSafeCommand()

---

source/common/engine/sc_man.cpp
source/core/searchpaths.cpp

My take on repairing the issues reported in 'https://forum.zdoom.org/viewtopic.php?f=341&t=68193'.
Tested locally and works as expected.

Fix loading of CRC cache if file does not exist.

---

source/build/include/baselayer.h
source/core/gamecontrol.cpp
source/platform/posix/cocoa/i_main.mm
source/platform/posix/sdl/i_main.cpp
source/platform/posix/sdl/sdlglvideo.cpp
source/platform/win32/i_input.cpp

Resolves the issues outlined in 'https://forum.zdoom.org/viewtopic.php?f=340&t=68205'.

Fix issues with Linux SDL builds following changes to refreshfreq.

---

source/duke3d/src/duke3d.h
source/duke3d/src/game.cpp

Repairs this: 
Also re-ordered gamefuncs to 1:1 match EDuke32.

Hacks to make IF launch again after gamefunc changes in 57cb22f13589bd3c3c6d88b6e731648b92308de1.

---

source/build/include/build.h
source/build/src/engine.cpp
source/sw/CMakeLists.txt
source/sw/src/draw.cpp
source/sw/src/game.cpp
source/sw/src/game.h
source/sw/src/interp.cpp
source/sw/src/interp.h
source/sw/src/interpso.cpp
source/sw/src/interpso.h
source/sw/src/jsector.cpp
source/sw/src/network.cpp
source/sw/src/panel.cpp
source/sw/src/player.cpp
source/sw/src/predict.cpp
source/sw/src/quake.cpp
source/sw/src/save.cpp
source/sw/src/saveable.cpp
source/sw/src/settings.h
source/sw/src/sprite.cpp
source/sw/src/text.h
source/sw/src/track.cpp
source/sw/src/vis.cpp
source/sw/src/weapon.cpp

So, NY00123 just dropped a massive amount of fixes and commits. It's probably good that I did PR #59 as this stuff goes hand in hand with it.
I know you cherry-pick from upstream, but did it so you didn't have to as I feel you might be a bit strapped for time as of late.

SW upstream backports

---

source/duke3d/src/game.cpp
source/rr/src/game.cpp

* Resolves https://forum.zdoom.org/viewtopic.php?f=340&t=68961

- Duke3D & RR: Always process cheats even while paused.

---

wadsrc/static/menudef.txt

fixes issue only for option Chat > Say = (T)
https://github.com/coelckers/Raze/issues/311

Chat error in option bindings: menudef.txt

---

source/games/duke/src/gamedef.cpp
source/games/duke/src/gamevar.cpp
source/games/sw/src/inv.cpp

This PR fixes compilation with Clang on FreeBSD.

Fix compilation with Clang on FreeBSD

---

source/core/initfs.cpp
source/core/searchpaths.cpp

Linux installs typically don't have it next to the program binary

Resolve raze.pk3 via search paths

---

source/core/gamecontrol.cpp
source/core/gamecontrol.h
source/core/gamestruct.h
source/core/searchpaths.cpp
source/games/duke/src/duke3d.h
source/games/duke/src/gamedef.cpp
wadsrc/static/engine/grpinfo.txt

Submitting this for review rather just commiting something. Tested and working, but wanted to know if this is the right or best approach here.
* Fixes #461.
* Fixes #462.

- Allow CON-based games to have multiplayer episodes filtered from menu.

---

source/games/blood/src/weapon.cpp

See https://github.com/coelckers/Raze/issues/503 for more details

Fix ignited spray/TNT issue when going underwater

---

source/games/blood/src/gameutil.cpp

My apologies, I used the wrong axis for distance checking.

[Blood] Fixed typo with sector fix commit

---

source/games/blood/src/animatesprite.cpp

This PR adds the currently missing effect kViewEffectSpotProgress. This is used in the [recent mod Eviction](https://www.moddb.com/mods/eviction-addon-for-blood).

[Blood] Add modern map kViewEffectSpotProgress support

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

remove dropdown list since i cant determine how to get a workflow to pull info from known releases
this avoids maintenance of these templates
& move game selection, i didnt realize it was misplaced between OS selection boxes

change version input in feature_request.yml & bug_request.yml

---

source/games/duke/src/d_menu.cpp
source/games/duke/src/premap_r.cpp

I have no experience with this code base so someone should probably review this before merging.

Small fixes
